import { FollowUpRepository } from '@/server/repositories/FollowUpRepository';
import { FollowUp } from '@/models/FollowUp';

export class FollowUpService {
  private followUpRepository: FollowUpRepository;

  constructor() {
    this.followUpRepository = new FollowUpRepository();
  }

  async createFollowUp(data: Omit<FollowUp, 'id' | 'createdAt' | 'updatedAt'>): Promise<FollowUp> {
    return this.followUpRepository.create(data);
  }

  async getFollowUpById(id: string): Promise<FollowUp | null> {
    return this.followUpRepository.findById(id);
  }

  async getFollowUpsByOutreach(outreachId: string): Promise<FollowUp[]> {
    return this.followUpRepository.findByOutreachId(outreachId);
  }

  async getFollowUpsByContact(contactId: string): Promise<FollowUp[]> {
    return this.followUpRepository.findByContactId(contactId);
  }

  async getUpcomingFollowUps(userId: string, days: number = 7): Promise<FollowUp[]> {
    return this.followUpRepository.findUpcoming(userId, days);
  }

  async getUpcomingFollowUpsWithContacts(userId: string, days: number = 7): Promise<Array<{ followUp: FollowUp; contact: { id: string; firstName: string; lastName?: string } }>> {
    return this.followUpRepository.findUpcomingWithContacts(userId, days);
  }

  async markComplete(id: string, completedDate: Date = new Date()): Promise<FollowUp> {
    return this.followUpRepository.markCompleted(id, completedDate);
  }

  async updateFollowUp(id: string, data: Partial<Omit<FollowUp, 'id' | 'createdAt' | 'updatedAt'>>): Promise<FollowUp> {
    return this.followUpRepository.update(id, data);
  }

  async markCompletedByOutreach(outreachId: string, reason?: string): Promise<FollowUp[]> {
    return this.followUpRepository.markCompletedByOutreachId(outreachId, reason);
  }

  async markCompletedByContact(contactId: string, reason?: string): Promise<FollowUp[]> {
    return this.followUpRepository.markCompletedByContactId(contactId, reason);
  }

  async deleteAutoGeneratedByOutreach(outreachId: string): Promise<void> {
    return this.followUpRepository.deleteByOutreachId(outreachId, true);
  }

  async getTriggeredReminders(userId: string): Promise<Array<{
    followUp: FollowUp;
    contact: { id: string; firstName: string; lastName?: string };
  }>> {
    return this.followUpRepository.findTriggeredReminders(userId);
  }
}

